INSERT INTO ObjectName
	( ObjectId , Language, ObjectName ) VALUES
	( 'P00' , 'english' , 'Pizza' ),
	( 'T00' , 'english' , 'Toast' ),
	( 'D00' , 'english' , 'Drink' ),
	( 'P01' , 'english' , 'Seafood pizza' ),
	( 'P02' , 'english' , 'Ham and tomato pizza' ),
	( 'P03' , 'english' , 'Pizza with 4 cheeses' ),
	( 'T01' , 'english' , 'Ham toast' ),
	( 'T02' , 'english' , 'Tomato and Cheese toast' ),
	( 'T03' , 'english' , 'Chicken toast' ),
	( 'D01' , 'english' , 'Coca Cola' ),
	( 'D02' , 'english' , 'Orange juice' ),
	( 'D03' , 'english' , 'Beer' ),
	( 'M01' , 'english' , 'Tomato' ),
	( 'M02' , 'english' , 'Ham' ),
	( 'M03' , 'english' , 'Garlic' ),
	( 'M04' , 'english' , 'Champions' ),
	( 'M05' , 'english' , 'Mozzarella Cheese' ),
	( 'M06' , 'english' , 'Fillet of Chicken' ),
	( 'M07' , 'english' , 'Blue Cheese' ),
	( 'M08' , 'english' , 'Parmesan Cheese' ),
	( 'M09' , 'english' , 'Cheddar Cheese' ),
	( 'M10' , 'english' , 'Mussels' ),
	( 'M11' , 'english' , 'Shrimps' ),
	( 'M12' , 'english' , 'Lobster' ),
	( 'M13' , 'english' , 'Pizza dough' ),
	( 'M14' , 'english' , 'White Bread' ),
	( 'P00' , 'finnish' , 'Pizza' ),
	( 'T00' , 'finnish' , 'Leipä' ),
	( 'D00' , 'finnish' , 'Juoma' ),
	( 'P01' , 'finnish' , 'Äyriäispizza' ),
	( 'P02' , 'finnish' , 'Kinkku ja tomaatti -pizza' ),
	( 'P03' , 'finnish' , '4 juuston pizza' ),
	( 'T01' , 'finnish' , 'Kinkkuleipä' ),
	( 'T02' , 'finnish' , 'Juusto-tomaattileipä' ),
	( 'T03' , 'finnish' , 'Kanaleipä' ),
	( 'D01' , 'finnish' , 'Coca Cola' ),
	( 'D02' , 'finnish' , 'Appelsiinimehu' ),
	( 'D03' , 'finnish' , 'Olut' ),
	( 'M01' , 'finnish' , 'Tomaatti' ),
	( 'M02' , 'finnish' , 'Kinkku' ),
	( 'M03' , 'finnish' , 'Valkosipuli' ),
	( 'M04' , 'finnish' , 'Herkkusieni' ),
	( 'M05' , 'finnish' , 'Mozzarella-juusto' ),
	( 'M06' , 'finnish' , 'Kanafile' ),
	( 'M07' , 'finnish' , 'Sinihomejuusto' ),
	( 'M08' , 'finnish' , 'Parmesan-juusto' ),
	( 'M09' , 'finnish' , 'Cheddar-juusto' ),
	( 'M10' , 'finnish' , 'Simpukat' ),
	( 'M11' , 'finnish' , 'Katkaravut' ),
	( 'M12' , 'finnish' , 'Hummeri' ),
	( 'M13' , 'finnish' , 'Pizza-taikina' ),
	( 'M14' , 'finnish' , 'Paahtoleipä' ),
	( 'A00' , 'finnish' , 'Lisukkeet' ),
	( 'P00' , 'italian' , 'Pizza' ),
	( 'T00' , 'italian' , 'Toast' ),
	( 'D00' , 'italian' , 'Bevanda' ),
	( 'P01' , 'italian' , 'Pizza ai frutti di mare' ),
	( 'P02' , 'italian' , 'Pizza al prosciutto cotto e pomodoro' ),
	( 'P03' , 'italian' , 'Pizza ai 4 formaggi' ),
	( 'T01' , 'italian' , 'Toast al prosciutto cotto' ),
	( 'T02' , 'italian' , 'Toast pomodori e formaggio' ),
	( 'T03' , 'italian' , 'Toast al pollo' ),
	( 'D01' , 'italian' , 'Coca Cola' ),
	( 'D02' , 'italian' , 'Succo d''arancia' ),
	( 'D03' , 'italian' , 'Birra' ),
	( 'M01' , 'italian' , 'Pomodoro' ),
	( 'M02' , 'italian' , 'Prosciutto cotto' ),
	( 'M03' , 'italian' , 'Aglio' ),
	( 'M04' , 'italian' , 'Funghi Champions' ),
	( 'M05' , 'italian' , 'Mozzarella' ),
	( 'M06' , 'italian' , 'Filetto di pollo' ),
	( 'M07' , 'italian' , 'Gorgonzola' ),
	( 'M08' , 'italian' , 'Parmigiano' ),
	( 'M09' , 'italian' , 'Cheddar' ),
	( 'M10' , 'italian' , 'Cozze' ),
	( 'M11' , 'italian' , 'Gamberetti' ),
	( 'M12' , 'italian' , 'Aragosta' ),
	( 'M13' , 'italian' , 'Impasto per la pizza' ),
	( 'M14' , 'italian' , 'Pane Bianco' ),
	( 'A00' , 'english' , 'Extras' );
